/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package energy.efficient;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author EGC
 */
public class Final extends javax.swing.JFrame {

      ArrayList<Integer> jobfinal = new ArrayList<Integer>();
      ArrayList<Integer> vmfinal = new ArrayList<Integer>();
      ArrayList<Integer> stock = new ArrayList<Integer>();
    public Final() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(240, 157, 234));
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel8.setText("Energy-Efficient Many-Objective Virtual Machine Placement");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 10, 420, 30);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel1.setText(" Optimization in a Cloud Computing Environment");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(60, 40, 350, 20);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 470, 80);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 170, 360, 160);

        jButton1.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jButton1.setText("Allocation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 100, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/aco?zeroDateTimeBehavior=convertToNull","root","");
            String sql="select vmsize from vmsize";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs1=pst.executeQuery();
            vmfinal.clear();
            while(rs1.next())
            {
                String d=rs1.getString(1);
                int da=Integer.parseInt(d);
                vmfinal.add(da);
            }
            
             String sql1="select load_v from vload";
            PreparedStatement pst1=con.prepareStatement(sql1);
            ResultSet rs2=pst1.executeQuery();
            jobfinal.clear();
            while(rs2.next())
            {
                String d1=rs2.getString(1);
                int da1=Integer.parseInt(d1);
                jobfinal.add(da1);
            }
            
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
                    
        }
        
         try {
              int a=Physical_Create.nofPhysical;
//            int a=2;
            int j = 0;
            jTextArea1.append("Job Size" + "\t\t" + "VM" + "\n");
            jTextArea1.append("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" + "\n");
            for (int i = 0; i < a; i++) 
            {
                System.out.println(jobfinal.get(i));
                System.out.println(j);
                if(j<vmfinal.size())
                {
                if (jobfinal.get(i) >= vmfinal.get(j) ) 
                {
                    System.out.println(jobfinal.get(i) + "   " + vmfinal.get(j));
                    jTextArea1.append(jobfinal.get(i) + "\t\t" + (j) + "\n");
                    int temp = jobfinal.get(i)-vmfinal.get(j) ;
//                     int temp = vmfinal.get(j) - jobfinal.get(i);
                    System.out.println(temp);
//                     vmfinal.set(j, temp1);
                    stock.add(temp);
                    int k=0;
                    System.out.println("Remining"+stock.get(k));
                    int ch=stock.get(k);
                     j++;
                       System.out.println("Remining"+vmfinal.size());
                    while(ch>0 && j<vmfinal.size())
                    {
                            
                        System.out.println("NextVM"+vmfinal.get(j)); 
                      if (stock.get(k)>=vmfinal.get(j)) 
                      {
                        System.out.println(jobfinal.get(i) + "   " + vmfinal.get(j));
                        jTextArea1.append(jobfinal.get(i) + "\t\t" + (j) + "\n");
                        int temp1 = stock.get(k)-vmfinal.get(j) ;
    //                     int temp = vmfinal.get(j) - jobfinal.get(i);
                        System.out.println(temp1);
                          stock.add(temp1);
                          k++;
                         j++;
                          System.out.println(j);
                          
                    }
                  
                      
                             
                    }
                  
                }
                else 
                {
                    j++;
                    i--;
                }
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "No Space , Create VM");
                }
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
