/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package energy.efficient;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;

/**
 *
 * @author EGC
 */
public class Load_VM extends javax.swing.JFrame {

    public static ArrayList vm=VM_Center.vmload;
    public static ArrayList allvm =new ArrayList();
    public static ArrayList vl1=VM_Center.vl;
    public static ArrayList hl1=Data_Center.hl;
    public static ArrayList ram=VM_Center.vraml;
    public static ArrayList mip=VM_Center.vmipl;
    public static ArrayList hostload=new ArrayList();
    public static ArrayList vmload=new ArrayList();
    public Load_VM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Virtual_Machine Load", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(280, 180, 380, 250);

        jButton2.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jButton2.setText("Load");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(390, 120, 160, 30);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jLabel1.setText("Load Pattern");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 370, 110, 30);

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel5.setText("Energy-Efficient Many-Objective Virtual Machine Placement Optimization in a Cloud Computing Environment");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 10, 750, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NextButton2.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(690, 410, 100, 110);

        jPanel3.setBackground(new java.awt.Color(240, 157, 234));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 790, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/aco?zeroDateTimeBehavior=convertToNull","root","");
            Statement stmt=con.createStatement();

            stmt.executeUpdate("DROP TABLE IF EXISTS hvload");
            stmt.executeUpdate("DROP TABLE IF EXISTS vload");
            String create="create table hvload(host_id varchar(50),load_h int(50))";
            String create1="create table vload(vm_id varchar(50),load_v int(50))";
            stmt.execute(create);
            stmt.execute(create1);
            //      PreparedStatement pst=con.prepareStatement(create);

            double vmLoad,allVmLoad=0;
            jTextArea1.append("VM_ID\tLOAD\n");
            jTextArea1.append("-------------------------------\n");

            for(int s=0;s<vl1.size();s++)
            {
                jTextArea1.append(vl1.get(s).toString()+"\n");
                vmload.add(vl1.get(s));
            }

            for(Object s:hl1)
            {
                int i=0;int j=0;
                String sd=(String)s;
                String spl[]=sd.split("\t");
                if(i==0)
                {
                    System.out.println("c:"+spl[0]);
                    System.out.println("D:"+spl[1]);
                    String sql1="insert into hvload(host_id,load_h)values('"+spl[0]+"','"+spl[1]+"')";
                    stmt.executeUpdate(sql1);
                    //           JOptionPane.showMessageDialog(this, "success");

                }

                i++;

            }
            //           System.out.println("row inserted"+i);

            //  jTextArea2.append("Host_ID\tLOAD\n");
            // jTextArea2.append("---------------------------------\n");

            for(int s=0;s<hl1.size();s++)
            {
                //  jTextArea2.append(hl1.get(s).toString()+"\n");
                hostload.add(hl1.get(s));
            }
            for(Object s:vl1)
            {
                int i=0;int j=0;
                String sd=(String)s;
                String spl[]=sd.split("\t");
                if(i==0)
                {
                    System.out.println(spl[0]);
                    String sql1="insert into vload(vm_id,load_v)values('"+spl[0]+"','"+spl[1]+"')";
                    stmt.executeUpdate(sql1);
                    //           JOptionPane.showMessageDialog(this, "success");

                }

                i++;

            }

            //       for(int i=0;i<vm.size();i++)
            //                {
                //                 spl = vm.get(i).toString().split(":");
                //
                //
                //
                //                    allVmLoad+=vmLoad;
                //
                //                     allvm.add(allVmLoad);
                //
                //                    jTextArea1.append(h.getId()+"\t"+h.getVmm()+"\t"+allVmLoad+"\n\n");
                //
                //
                //                }

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new VM_Monitor().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load_VM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Load_VM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Load_VM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Load_VM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Load_VM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
