/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package energy.efficient;

import static energy.efficient.Load_VM.hl1;
import static energy.efficient.Load_VM.hostload;
import static energy.efficient.Load_VM.vl1;
import static energy.efficient.Load_VM.vmload;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author EGC
 */
public class Table_Load extends javax.swing.JFrame {

    public static ArrayList d=Data_Center.k;
    public static ArrayList v=VM_Center.vmload;

    public Table_Load() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 150, 410, 210);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ezgif.com-resize.gif"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 150, 170, 160);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jLabel1.setText("Load Pattern");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 100, 110, 30);

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel4.setText("Energy-Efficient Many-Objective Virtual Machine Placement Optimization in a Cloud Computing Environment");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 750, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NextButton2.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(660, 270, 100, 110);

        jPanel3.setBackground(new java.awt.Color(240, 157, 234));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 760, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try
        {
            //=================Load Schl of VM=========================
            List vmList=new ArrayList();
            ArrayList vDetails=new ArrayList();
            int tVms;
            double vmLoad,allVmLoad=0;

            jTextArea1.append("Vm_Id\tBw\tRAM\tMIPs\tNo.PEs\n");
            jTextArea1.append("==============================================================\n\n");
            //  jTextArea2.append("h_id\tRam\tStorage\tBw\tNo.pes\n"+
                //                   "======================================================\n\n");
            for(int j=0;j<v.size();j++)
            {
                jTextArea1.append(v.get(j).toString()+"\n");
            }
            for(int k=0;k<d.size();k++)
            {
                // jTextArea2.append(d.get(k).toString()+"\n");
            }
            //            for(int j=0;j<broker.length;j++)
            //            {
                //                vmList=broker[j].getVmList();
                //                tVms=vmList.size();
                //                for(int i=0;i<vmList.size();i++)
                //                {
                    //                    org.cloudbus.cloudsim.Vm h=(org.cloudbus.cloudsim.Vm)vmList.get(i);
                    //                    vDetails.add("id: "+h.getId()+
                        //                            "\tvmUid : "+h.getUid()+
                        //                            "\tbw : "+h.getBw()+
                        //                            "\tram : "+h.getRam()+
                        //                            "\tmips : "+h.getMips()+
                        //                            "\tnpes : "+h.getNumberOfPes());
                    //
                    //                    vmLoad=h.getBw()+h.getRam()+h.getMips();
                    //                    allVmLoad+=vmLoad;
                    //                    jTextArea1.append(h.getId()+
                        //                            "\t"+h.getUid()+
                        //                            "\t"+h.getBw()+
                        //                            "\t"+h.getRam()+
                        //                            "\t"+h.getMips()+
                        //                            "\t"+h.getNumberOfPes()+"\n\n");
                    //                }
                //                allvm.add(allVmLoad);
                //                jTextArea2.append(j+"\t"+broker[j].getId()+"\t"+tVms+"\t"+allVmLoad+"\n\n");
                //                BrokerLoad.add(allVmLoad);
                //                allVmLoad=0;
                //            }
        }
        catch(Exception e)
        {
            System.out.println("Exception : "+e);
        }
        
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/aco?zeroDateTimeBehavior=convertToNull","root","");
            Statement stmt=con.createStatement();

            stmt.executeUpdate("DROP TABLE IF EXISTS hvload");
            stmt.executeUpdate("DROP TABLE IF EXISTS vload");
            String create="create table hvload(host_id varchar(50),load_h int(50))";
            String create1="create table vload(vm_id varchar(50),load_v int(50))";
            stmt.execute(create);
            stmt.execute(create1);
            //      PreparedStatement pst=con.prepareStatement(create);

            double vmLoad,allVmLoad=0;
//            jTextArea1.append("VM_ID\tLOAD\n");
//            jTextArea1.append("-------------------------------\n");
//
//            for(int s=0;s<vl1.size();s++)
//            {
//                jTextArea1.append(vl1.get(s).toString()+"\n");
//                vmload.add(vl1.get(s));
//            }

            for(Object s:hl1)
            {
                int i=0;int j=0;
                String sd=(String)s;
                String spl[]=sd.split("\t");
                if(i==0)
                {
                    System.out.println("c:"+spl[0]);
                    System.out.println("D:"+spl[1]);
                    String sql1="insert into hvload(host_id,load_h)values('"+spl[0]+"','"+spl[1]+"')";
                    stmt.executeUpdate(sql1);
                    //           JOptionPane.showMessageDialog(this, "success");

                }

                i++;

            }
           

            for(int s=0;s<hl1.size();s++)
            {
                //  jTextArea2.append(hl1.get(s).toString()+"\n");
                hostload.add(hl1.get(s));
            }
            for(Object s:vl1)
            {
                int i=0;int j=0;
                String sd=(String)s;
                String spl[]=sd.split("\t");
                if(i==0)
                {
                    System.out.println(spl[0]);
                    String sql1="insert into vload(vm_id,load_v)values('"+spl[0]+"','"+spl[1]+"')";
                    stmt.executeUpdate(sql1);
                    //           JOptionPane.showMessageDialog(this, "success");

                }

                i++;

            }

          
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new VM_Monitor().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table_Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table_Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table_Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table_Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table_Load().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
